In [49]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

In [50]:
data = {
    "Study_Hours":[1,2,3,4,5,6,7,8,9,10,11,12],
    "Attendance":[60,65,70,72,75,80,82,85,88,90,92,95],
    "Assignments":[2,3,4,5,5,6,7,7,8,8,9,10],
    "Marks":[35,40,45,50,58,65,72,78,82,88,92,96]
}
df = pd.DataFrame(data)
df.to_csv("student_performance.csv", index=False)

PART-1: Dataset Exploration

In [51]:
df=pd.read_csv('student_performance.csv')
print("Dataset loaded successfully")

Dataset loaded successfully

In [52]:
print("First 5 rows: ")
df.head()

First 5 rows:

   Study_Hours  Attendance  Assignments  Marks
0            1          60            2     35
1            2          65            3     40
2            3          70            4     45
3            4          72            5     50
4            5          75            5     58

In [53]:
print("Last 5 rows: ")
df.tail()

Last 5 rows:

    Study_Hours  Attendance  Assignments  Marks
7             8          85            7     78
8             9          88            8     82
9            10          90            8     88
10           11          92            9     92
11           12          95           10     96

In [54]:
print("Shape of the dataset: ")
df.shape

Shape of the dataset:

(12, 4)

In [55]:
print("Column names: ")
df.columns.tolist()

Column names:

['Study_Hours', 'Attendance', 'Assignments', 'Marks']

In [56]:
print("Datatypes: ")
df.dtypes

Datatypes:

Study_Hours    int64
Attendance     int64
Assignments    int64
Marks          int64
dtype: object

In [57]:
print("Statistical Summary: ")
df.describe()

Statistical Summary:

       Study_Hours  Attendance  Assignments      Marks
count    12.000000   12.000000    12.000000  12.000000
mean      6.500000   79.500000     6.166667  66.750000
std       3.605551   11.172206     2.443296  21.080474
min       1.000000   60.000000     2.000000  35.000000
25%       3.750000   71.500000     4.750000  48.750000
50%       6.500000   81.000000     6.500000  68.500000
75%       9.250000   88.500000     8.000000  83.500000
max      12.000000   95.000000    10.000000  96.000000

PART-2: Identify Features and Label

In [58]:
# Separating the features and target variable
x=df[['Study_Hours', 'Attendance', 'Assignments']]
y=df['Marks']
print("Features: \n")
print(x)
print("\nLabel: \n")
print(y)

Features:

    Study_Hours  Attendance  Assignments
0             1          60            2
1             2          65            3
2             3          70            4
3             4          72            5
4             5          75            5
5             6          80            6
6             7          82            7
7             8          85            7
8             9          88            8
9            10          90            8
10           11          92            9
11           12          95           10

Label:

0     35
1     40
2     45
3     50
4     58
5     65
6     72
7     78
8     82
9     88
10    92
11    96
Name: Marks, dtype: int64

PART-4: Train-Test Split

In [59]:
#Splitting the dataset into training(80%) and testing data(20%)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42) #random state is used to split the dataset in the same way everytime
print("x_train Shape:", x_train.shape)
print("x_test Shape:", x_test.shape)
print("y_train Shape:", y_train.shape)
print("y_test Shape:", y_test.shape)

x_train Shape: (9, 3)
x_test Shape: (3, 3)
y_train Shape: (9,)
y_test Shape: (3,)

PART-5: Train Your First Model

In [60]:
model=LinearRegression() #calling the model
model.fit(x_train,y_train) #training the model
print("Slope (Coefficients):") #weights
print(model.coef_)
print("\nIntercept:") #bias
print(model.intercept_)

Slope (Coefficients):
[ 3.45487968  1.34491979 -2.40274064]

Intercept:
-48.100601604278054

PART-6: Predictions

In [61]:
#creating new student data for prediction
predict_data= pd.DataFrame({'Study_Hours': [5, 8, 12],'Attendance': [80, 90, 95],'Assignments': [5, 8, 10]})
predictions=model.predict(predict_data) #predicting marks using the trained model
print("Predicted marks:")
print(predictions)

Predicted marks:
[64.75367647 81.35929144 97.09792781]

PART-7: Actual vs Predicted Comparison

In [62]:
y_pred = model.predict(x_test) #predicting marks for the test dataset
comparison = pd.DataFrame({'Actual marks': y_test.values,'Predicted marks': y_pred}) #creating a comparison table
comparison['Difference'] = abs(comparison['Actual marks']-comparison['Predicted marks'])
print(comparison)

   Actual marks  Predicted marks  Difference
0            92        92.011029    0.011029
1            88        88.269051    0.269051
2            35        31.243984    3.756016

In [63]:
#finding the student with the highest prediction error
highest_error = comparison.loc[comparison['Difference'].idxmax()]
print("Student with highest prediction error:")
print(highest_error)

Student with highest prediction error:
Actual marks       35.000000
Predicted marks    31.243984
Difference          3.756016
Name: 2, dtype: float64

PART-8: Model Evaluation

In [64]:
#evaluating the model using MAE and R2 score
mae = mean_absolute_error(y_test, y_pred) #MAE calculates the average difference between actual and predicted values
r2 = r2_score(y_test, y_pred) # R2 score shows how well the model fits the data
print("Mean Absolute Error (MAE):", mae)
print("R2 Score:", r2)

Mean Absolute Error (MAE): 1.3453654188948245
R2 Score: 0.9929962957709836

PART-9: Data Visualization Challenge

Plot-1: Study Hours vs Marks

In [65]:
fig1 = px.scatter(df,x='Study_Hours',y='Marks',title='Study Hours vs Marks',labels={'Study_Hours':'Study Hours','Marks':'Marks'})
fig1.show()

Plot-2: Attendance vs Marks

In [66]:
fig2 = px.scatter(df,x='Attendance',y='Marks',hover_data=['Study_Hours','Assignments'],title='Attendance vs Marks',labels={'Attendance':'Attendance','Marks':'Marks'})
fig2.show()

Plot-3: Assignments vs Marks

In [67]:
fig3 = px.scatter(df,x='Assignments',y='Marks',color='Assignments',title='Assignments vs Marks',labels={'Assignments':'Assignments','Marks':'Marks'})
fig3.show()

Plot-4: Regression Line Visualization

In [68]:
fig4 = px.scatter(df,x='Study_Hours',y='Marks',trendline='ols',title='Regression Line Visualization',labels={'Study_Hours':'Study Hours','Marks':'Marks'})
fig4.show()

Plot-5: Predicted Marks Trend

In [69]:
#Predicting marks for study hours from 1 to 15
future = pd.DataFrame({'Study_Hours': range(1, 16),'Attendance': [85] * 15,'Assignments': [7] * 15})
future_pred = model.predict(future)
trend = pd.DataFrame({'Study_Hours': range(1, 16),'Predicted_Marks': future_pred})
fig5 = px.line(trend,x='Study_Hours',y='Predicted_Marks',title='Predicted Marks Trend',labels={'Study_Hours':'Study Hours','Predicted_Marks':'Predicted Marks'})
fig5.show()

Bonus Challenge

In [70]:
data={"Experience":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
        "Projects":[1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11],
        "Skills":[2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12],
        "Salary":[25000,28000,32000,35000,39000,43000,47000,52000,56000,60000,65000,70000,75000,80000,85000,90000,95000,100000,105000,110000]}
df =pd.DataFrame(data)
x =df[['Experience', 'Projects', 'Skills']] #selecting features and label
y =df['Salary']
print("Features: \n")
print(x)
print("\nLabel: \n")
print(y)

Features:

    Experience  Projects  Skills
0            1         1       2
1            2         2       3
2            3         2       3
3            4         3       4
4            5         3       4
5            6         4       5
6            7         4       5
7            8         5       6
8            9         5       6
9           10         6       7
10          11         6       7
11          12         7       8
12          13         7       8
13          14         8       9
14          15         8       9
15          16         9      10
16          17         9      10
17          18        10      11
18          19        10      11
19          20        11      12

Label:

0      25000
1      28000
2      32000
3      35000
4      39000
5      43000
6      47000
7      52000
8      56000
9      60000
10     65000
11     70000
12     75000
13     80000
14     85000
15     90000
16     95000
17    100000
18    105000
19    110000
Name: Salary, dtype: int64

In [71]:
#splitting the dataset
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)
#creating and training the model
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [72]:
#predicting salary for a new employee
new_employee = pd.DataFrame({'Experience':[8],'Projects':[5],'Skills':[6]})
prediction = model.predict(new_employee)
print("Predicted Salary:", prediction[0])

Predicted Salary: 52309.39226519337